services:
    php-app:
      build:
        context: .
        dockerfile: /dockerImages/php/Dockerfile.yml
      container_name: php-app
      depends_on:
        - mariadb
      ports: 
        - 3000:8000
      networks:
        - external-network
      command: 
        bash -c "composer start"

    mariadb:
      container_name: mariadb-php-app
      image: mariadb:11
      ports:
        - "3306:3306"
      environment:
        - MYSQL_ROOT_PASSWORD=root   
      volumes:
      - ./volumes/mariadb_data:/var/lib/mysql
      - ./volumes/db.sql:/docker-entrypoint-initdb.d/db.sql
      networks:
        - external-network

networks:
  external-network:

volumes:
  mariadb_data:
