FROM php

RUN apt-get update && apt-get install -y \
    git \
    unzip \
    zip

COPY --from=composer:2.8.4 /usr/bin/composer /usr/bin/composer

WORKDIR /app

COPY . /app

RUN composer install





